{$ALIGN ON}
{$B-}//complete boolean eval off
{$C-}//assertions off
{$D+}//no debug info
{$G-}//imported data off{$I+}//io checks on
{$J-}//writable constants off
{$L-}//local symbols off
{$H+}//longstrings on
{$O+}//optimization on
{$P+}//openstrings on
{$Q-}//overflow checking off
{$T-}//typed @ off{$M-}//type info off
{$Y-}//no reference informations
{$R-}//rangecheck off
{$U-}//pentium(tm) safe divide off
{$W-}//stackframes off
{$X+}//extended syntax on
{$V-}//var shortstring check off
{$HINTS OFF}
{$WARNINGS OFF}
{$IMAGEBASE $00400000}
{$MINSTACKSIZE 1024}{$WARNINGS OFF}//warnings off
{$MINENUMSIZE 1}//minimum enum type size = 1